In [24]:
# 1. Write a Python Program to Add two Matrices ?
import numpy as np
record1 = np.matrix([[1,2,6],[5,9,8],[54,415,52],[541,5,5]])
record2 = np.matrix([[1,6,688],[45,99,658],[554,415,52],[541,56,15]])
result = np.matrix([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])
matrix1 = np.reshape(record1,(4,3))
matrix2 = np.reshape(record2,(4,3))
matrix3 = np.reshape(result,(4,3))

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]
for r in result:
    print(r)

[[  2   8 694]]
[[ 50 108 666]]
[[608 830 104]]
[[1082   61   20]]


In [82]:
# 2. Write a Python Program to Multiply two Matrices ?
record1 = np.array([[1,2,6],[5,9,8],[54,415,52],[541,5,5]])
record2 = np.array([[1,6,688],[45,99,658],[554,415,52]])
result = np.array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])
matrix1 = np.reshape(record1,(4,3))
matrix2 = np.reshape(record2,(3,3))
matrix3 = np.reshape(result,(4,3))

for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
        
            result[i][j] += matrix1[i][k] * matrix2[k][j]
#for r in result:
#    print(r)
print(result)    


[[  3415   2694   2316]
 [  4842   4241   9778]
 [ 47537  62989 312926]
 [  3536   5816 375758]]


[[0, 0, 7], [0, 0, 8], [0, 0, 9]]


In [106]:
# 3. Write a Python Program to transpose a Matrix ?

def generate_transpose(in_matrix):
    out_matrix = []
    for ele in range(len(in_matrix[0])):
        out_matrix.append([0 for i in range(len(in_matrix))])
    for i in range(len(in_matrix)):
        for j in range(len(in_matrix[i])):
            out_matrix[j][i] = in_matrix[i][j]
    print(out_matrix)   
generate_transpose(result)


[[3415, 4842, 62989, 4842], [4842, 4842, 62989, 5816], [5816, 4842, 5816, 375758]]


In [2]:
# 4. Write a Python Program to sort Words in an Alphabatical Order ?
def sortString():
    in_string = input("Enter a String: ").title()
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))

sortString()

Enter a String:  Write a Python Program to sort Words in an Alphabatical Order
 A Alphabatical An In Order Program Python Sort To Words Write


In [4]:
#  5. Write a Python Program to Remove Punctuation From a String?

def remove_punc():
    punct='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    res=''
    s = input("Enter a string: ")
    for i in s:
        if i not in punct:
            res+=i
    print(res)
remove_punc('Write a Python &Program to Remo:ve Punctuation From a -String?'')

SyntaxError: EOL while scanning string literal (2075489851.py, line 11)

write write write all the number from from from 1 to 100


False